org: sjdonado
app: sjdonado-github-web-scraper
service: sjdonado-github-web-scraper

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  versionFunctions: false
  runtime: nodejs14.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  patterns:
    - '!build-chrome-layer.sh'
    - '!node_modules/chrome-aws-lambda/**'
    - '!node_modules/puppeteer/.local-chromium/**'

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.build.json'

functions:
  cronHandler:
    handler: handler.run
    memorySize: 1024
    timeout: 30
    events:
      - schedule: cron(0 0 1 * ? *)
    layers:
      - arn:aws:lambda:us-east-1:358981175787:layer:ChromeLambdaLayer:1
