org: sjdonado
app: sjdonado-github-web-scraper
service: sjdonado-github-web-scraper

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  versionFunctions: false
  layers:
   - arn:aws:lambda:${self:provider.region}:764866452798:layer:chrome-aws-lambda:10
  runtime: nodejs14.x
  timeout: 10
  # timeout: 30
  # memorySize: 2048

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  patterns:
    - '!node_modules/puppeteer/.local-chromium/**'

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.build.json'

functions:
  cronHandler:
    handler: handler.run
    events:
      # Every week at 00:00 on Monday
      - schedule: cron(0 0 ? * MON *)
  dev:
    handler: handler.run
