---
name: "deploy"

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup remote SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan sjdonado.de >> ~/.ssh/known_hosts
      - name: Add dokku remote
        run: git remote add dokku ssh://dokku@sjdonado.de:22/sjdonado.de
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./dist
          git commit -m "[auto] dokku new build"
      - name: Push to dokku
        run: git push dokku `git subtree split --prefix dist master`:master --force
