org: sjdonado
app: sjdonado-github-stats
service: sjdonado-github-stats

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  timeout: 10
  environment:
    GITHUB_API_KEY: ${param:GITHUB_API_KEY}
    FIREBASE_PROJECTID: ${param:FIREBASE_PROJECTID}

functions:
  cronHandler:
    handler: handler.run
    events:
      # Invoke Lambda function at 8:00 am (UTC) every 1st day of the month
      - schedule: cron(0 8 1 * ? *)
